import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from '../redux/Provider';
import Header from "./components/header";
import ClientWrapper from "./components/clientWrapper"; // Adjust the path as necessary

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body className={inter.className}>
        <Providers>
          <ClientWrapper>
            <div>
              <Header />
              {children}
            </div>
          </ClientWrapper>
        </Providers>
      </body>
    </html>
  );
}
